name: Apply Patch From Chat

on:
  workflow_dispatch:
    inputs:
      patch_b64:
        description: Base64-encoded unified diff (optional if patch_url provided)
        required: false
      patch_url:
        description: URL to a raw .diff/.patch file (optional if patch_b64 provided)
        required: false
      branch:
        description: Branch name to create
        required: false
        default: chat-patch
      commit_message:
        description: Commit message
        required: false
        default: Apply patch from chat
      pr_title:
        description: Pull Request title
        required: false
        default: Patch from ChatGPT
      pr_body:
        description: Pull Request body
        required: false
        default: Automated patch from chat

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: apply-patch-from-chat
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Obtain patch
        id: patch
        env:
          PATCH_B64: ${{ github.event.inputs.patch_b64 }}
          PATCH_URL: ${{ github.event.inputs.patch_url }}
        run: |
          set -euo pipefail
          if [[ -n "${PATCH_URL}" ]]; then
            curl -fsSL "${PATCH_URL}" -o /tmp/patch.diff
          elif [[ -n "${PATCH_B64}" ]]; then
            python3 - <<'PY' > /tmp/patch.diff
      import os, re, base64, sys
      s = os.environ.get("PATCH_B64","")
      # strip anything that's not valid base64 (kills accidental backticks, spaces, etc.)
      s = re.sub(r'[^A-Za-z0-9+/=\n\r]', '', s)
      sys.stdout.buffer.write(base64.b64decode(s))
      PY
          else
            echo "No patch_url or patch_b64 provided" >&2
            exit 1
          fi
      
      - name: Create branch
        run: |
          git checkout -b "${{ github.event.inputs.branch }}"

      - name: Apply patch
        run: |
          set -e
          if git apply --whitespace=fix --reject /tmp/patch.diff; then
            echo "Applied with git apply"
          else
            echo "git apply failed; trying git am"
            git am /tmp/patch.diff
          fi

      - name: Commit changes (if using git apply)
        run: |
          if ! git diff --cached --quiet; then
            git commit -m "${{ github.event.inputs.commit_message }}"
          fi

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.inputs.branch }}
          title: ${{ github.event.inputs.pr_title }}
          body: ${{ github.event.inputs.pr_body }}
          base: ${{ github.ref_name }}
          labels: patch-from-chat
